[[tls.certificates]]
  certFile = "/certs/seis-lab-data.ipma.pt/cert_fullchain.pem"
  keyFile = "/keys/seis-lab-data.key"

[[tls.certificates]]
  certFile = "/certs/auth.seis-lab-data.ipma.pt/cert_fullchain.pem"
  keyFile = "/keys/auth.seis-lab-data.key"

[[tls.certificates]]
  certFile = "/certs/data.seis-lab-data.ipma.pt/cert_fullchain.pem"
  keyFile = "/keys/data.seis-lab-data.key"

[[tls.certificates]]
  certFile = "/certs/services.seis-lab-data.ipma.pt/cert_fullchain.pem"
  keyFile = "/keys/services.seis-lab-data.key"
